apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: SMEAR-download
  template: SMEAR-download
message: |-
  The following service(s) have been created in your project: ${NAME}
metadata:
  annotations:
    description: Application template for smear application
    iconClass: icon-spring
    openshift.io/display-name: SMEAR-download
    openshift.io/long-description: SMEAR-download
    openshift.io/provider-display-name: CSC
    tags: SMEAR-download
    template.openshift.io/bindable: "false"
  name: SMEAR-download
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: dev
      contextDir: .
    strategy:
      dockerStrategy:
        dockerfilePath: openshift/smear.Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
        namespace: ${BUILD_IMAGE_NAMESPACE}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}

  spec:
    replicas: ${REPLICA}
    selector:
      app: ${NAME}

    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          env:
          - image: ''
            imagePullPolicy: Always
            name: ${NAME}
            ports:
              - containerPort: 8887
                protocol: TCP
        restartPolicy: Always
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${NAME}:latest
            namespace: ${BUILD_IMAGE_NAMESPACE}
        type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    description: Exposes and load balances the application pods
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
      - name: web
          port: 8080
        protocol: TCP
        targetPort: 8887
    selector:
      app: ${NAME}
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: web
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
parameters:
- description: The OpenShift Namespace where the build image ImageStream resides.
  displayName: Build Image Namespace
  name: BUILD_IMAGE_NAMESPACE
  required: true
  value: avaa-smear-download-conf
- description: The name assigned to all of the smear objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: SMEAR-download
- description: Number of Replicas
  displayName: REPLICA
  name: REPLICA
  required: true
  value: '1'
- description: The exposed hostname that will route to the Smear service, if left blank a value will
 be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
  required: true
  value: avaa-smear-download.rahtiapp.fi
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/CSCfi/smear-download-rahti.git

